version: '3.0'
# docker-compose up geth-dev
services:
  geth:
    image: ethereum/client-go
    entrypoint: geth --dev -dev.period 1 --rpc --rpcapi "net,eth,web3,debug,personal" --networkid 1001 --ws --wsapi "web3,eth,net,admin,personal,debug" --wsaddr "0.0.0.0" --wsport 8546 --wsorigins "*" --targetgaslimit 7500000
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
  geth-dev:
    image: speakerwiggin/generate-geth-accounts:latest
    environment:
      GETH: geth
    depends_on:
      - geth
